# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issues:
    types: [created, edited]

jobs:
  deploy-aks:
    if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'create-cluster')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Comment issue
        uses: kyoncy/issue-comment-actions@v1
        with:
          message: "Hey, I am now working on your cluster creation, let's see what I can do for you"

      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
