# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issues:
    types: [created, edited, labeled]

jobs:
  deploy-aks:
    if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'create-cluster')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            **Hey there!** I'm taking good care of your issue and will create the cluster.
          
      - name: GitHub Issue Parser
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v2   
        with:
          template-path: .github/ISSUE_TEMPLATE/CLUSTER_CREATION.yml
        
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Here is the information I got:
            **Resource group name**: ${{ steps.issue-parser.outputs.issueparser_resource-group-name }}
            **Location**: ${{ steps.issue-parser.outputs.issueparser_location }}
            **Cluster name**: ${{ steps.issue-parser.outputs.issueparser_cluster-name }}
            **Amount of nodes**: ${{ steps.issue-parser.outputs.issueparser_amount-nodes }}
